server:
    port: 9000
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: admin
        url: jdbc:h2:file:~/h2db
        username: h2sa
    h2:
        console:
            enabled: true
            path: /h2
    rabbitmq:
        host: localhost
        password: secret
        port: 5672
        username: admin
